import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TransitionProvider from "./transition-provider";
import Sidebar from '@/components/Sidebar'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Sidebar
        stats={{
          dashboardCount: 3,         // 오늘 작성한 조각 수
          communityCount: 1,         // 커뮤니티 새 글 수
          trashCount: 0,             // 휴지통 안 글 수
          todayLabel: '오늘',  // 오늘 날짜나 짧은 요약
        }}
      />        {/* Page-flip transition wrapper (client component) */}
        <TransitionProvider>
          {children}
        </TransitionProvider>
        <footer
          style={{
            textAlign: "center",
            fontSize: "12px",
            color: "#a1a1a1",
            padding: "20px 0",
            letterSpacing: "0.5px",
            borderTop: "1px solid rgba(0,0,0,0.05)",
            fontFamily: "var(--font-geist-mono)",
            background: "rgba(255,255,255,0.4)",
            backdropFilter: "blur(10px)",
          }}
        >
          © SoulKim 2025
        </footer>
      </body>
    </html>
  );
}